### ISSUE TITLE
Some questions about ABM processing in the GSC module 

### ISSUE THREAD

**Issue by yemifeng** [athena-team/athena-signal#12]
Thanks for sharing the GSC processing code!  There are existing some code in the "dios_ssp_gsc_abm.c" that make me confusing.

line 338 in the function "dios_ssp_gsc_gscabm_processonedatablock"
/* compute error signal in time-domain with circular convolution constraint e = [0 | new] */
for (i = 0; i < gscabm->fftsize / 2; i++)
`{`
	gscabm->e[gscabm->fftsize / 2 + i] = gscabm->xrefdline[i] - gscabm->ytmp[gscabm->fftsize / 2 + i]; 
}
The code is checked carefully and it is found that 
"gscabm->e" is the output for the ABM module. "gscabm->xrefdline" is from the output of fixed beamforming output, "gscabm->ytmp" is from the ABM filter output with the input from the steering output. 

However , I think that  "gscabm->xrefdline" should be from the steering output, and "gscabm->ytmp" should be from the ABM filter output with the input from the fixed beamforming output.  Maybe I got it wrong, and please help me to understand it. The reference paper is "A robust adaptive beamformer for microphone arrays with a blocking matrix using constrained adaptive filters"

Thanks very much!

**Comment by songhui5561** [comment]
I guess you mean 'steering output' by each sensor channel. So yes, as you think, 'gscabm->xrefdline' should be each microphone signal, and 'gscabm->ytmp' is the filtered result from the output of FBF. We find it also works in the opposite way. 
I recall that we have tested both ways, and found the results hardly make any difference in output SNR. We choose this ABM because it leads to a little lower WER in An ASR dataset.

**Comment by yemifeng** [comment]
Thanks for sharing these technical details of the algorithm, and it is interesting.  I have another question, as far as I know, GSC is not very effective for non-coherence noise, so a post-filter is usually needed. However, there are no post-filter founded in the whole process. So I guess the following NS module  will remove the non-coherence noise, or the post-filter will lead to lower WER? So is my guess right?

**Comment by songhui5561** [comment]
NS is an option for post-filtering, with limited effect. For ASR mode, we prefer to use a light-NS, say MCRA, to remove SOME noise with hardly speech distortion and to add noise to the training set. For communication mode, NN-based noise suppression leads to higher output SNR. It will be submitted soon.

**Comment by yemifeng** [comment]
Thanks!
