### ISSUE TITLE
some question about "dios_ssp_matrix_inv_process"

### ISSUE THREAD

**Issue by yemifeng** [athena-team/athena-signal#13]
Hello, the function of "dios_ssp_matrix_inv_process" is tested using the following code:

#include  "dios_ssp_share_cinv.h"
int main(int argc, char **argv)
{
     float R[18] = { 
                     258919244, 0.000000000000000, -683065112,  0.000000000000000,  123292480, 0.000000000000000,
 		    -683065112, 0.000000000000000,  1802021921,0.000000000000000, -325262900, 0.000000000000000,
		     123292480, 0.000000000000000, -325262900,  0.000000000000000,  58709685,    0.000000000000000,
		    };
    float Rinv[18] = { 0.0 };
    void* handle = dios_ssp_matrix_inv_init(3);
    dios_ssp_matrix_inv_process(handle, R, Rinv);
    return 0;
}

However, the inverse matrix result is different from through using "inv" function in matlab. Is there anything that we should pay special attantion to? Because I found that if I using the mvdr matlab code(all the matlab code is same with the c code except the "inv" function ) , the final noise reduction performance is degrade.

Look forward to your reply, Thanks!

**Comment by songhui5561** [comment]
I don't remember any special processing in 'inv' function. let me check later.  

One more thing, we have better make sure Rnn is nonsingular, with small 'condition number', by diagonal loading.

**Comment by Anita-Hailey** [comment]
Open source code will have a certain loss in accuracy, you can try to use a simple matrix to verify the code.

The C code will protect matrix that in the actual processing, so the effect of the c code is better

**Comment by yemifeng** [comment]
Thanks for reply, I will try it.
