### ISSUE TITLE
能指导一下为什么我实测自己采集的AEC的效果不好？

### ISSUE THREAD

**Issue by zuowanbushiwo** [athena-team/athena-signal#14]
1.效果不好情况下应该怎么分析？需要调哪些参数?
2.能上传一个你调试后效果比较好参数和aec处理后的文件吗？

[examples.zip](https://github.com/athena-team/athena-signal/files/5339591/examples.zip)

初学者，还在入门中，谢谢！

**Comment by songhui5561** [comment]
其实你的处理还是有效果的，回声大概抑制了接近20dB。你所说的效果不好应该指的是残余回声比较大吧，你可以尝试使用通信模式，可以看到识别模式和通信模式的一些参数设置不同，这些参数会影响残余回声的消除量；
    也可以观察double talk （DTD）的结果，对于单讲状态，可以增加残余回声的消除量。
    通常ASR模式不会把残余回声压的过低，以免损伤近端的有效语音。

**Comment by zuowanbushiwo** [comment]
好的，感谢！ 我主要是对比了你们demo 的数据的结果，觉得差别太明显了，以为是我这边采集有问题，比如说延迟太大导致数据没有对齐，导致前面的单讲状态消除状态也很差。 为什么了 你们demo的数据效果可以那么好，是保证了哪些条件？我这对比了一下数据，demo 的ref 信号的幅度比较小 ，和这个有关吗？ 感谢指导！

**Comment by songhui5561** [comment]
跟ref的幅度关系不大。数据对齐当然是必要的，不能延时太大，也不能非因果。
其他的原因，一是音乐回声比人声回声更容易消除一些，因为音乐信号的连续性有利于滤波器的收敛和跟踪；另一个是设备的非线性回声成分比较少，多数都是线性回声，消除起来更容易些；最后就是一些细节参数的调整了，比较关键的像DTD、erl、res中的增益计算，等等。

**Comment by zuowanbushiwo** [comment]
你好，非常感谢您的耐心指导。
       我这边自己用Audacity 观察时域波形，对比两个波形尖峰位置，可以发现far_end 信号在 near_end 信号前面50个采样点左右，按照16k的采样率计算只有4ms左右，是满足非因果和不能延时太大的条件吗？



![屏幕截图 2020-10-10 171726](https://user-images.githubusercontent.com/3354428/95651398-bb0b4580-0b1c-11eb-97cd-a2e89aa4f0ac.png)

**Comment by songhui5561** [comment]
这种是可以的

**Comment by zuowanbushiwo** [comment]
好的，非常感谢！

**Comment by KKevinLee** [comment]
hi, zuowanbushiwo.
recently, i note you can access to the exetools forum. i am searching a tool in the forum that you recently download(10-22-2020).
Can you send it to me by email(KKevinLee@protonmail.com) if It was no trouble? I am working on the similar tech but have not make any breakthrough and i really need to refer to the tech provided by the file.

Thanks!!!!.@zuowanbushiwo
