### ISSUE TITLE
关于代码中子带的问题请教？

### ISSUE THREAD

**Issue by zuowanbushiwo** [athena-team/athena-signal#15]
1. dios_ssp_share_subband.h 中 struct objSubBand   scale 变量是什么作用？
    是窗函数的恢复系数吗？ 在 dios_ssp_share_subband.c 代码中使用窗函数使用的是平顶窗，我查资料平顶窗的幅值恢复系数是1.110，感觉也不太像，这个和使用的窗函数有关吗？

**Comment by songhui5561** [comment]
是的，它指的是恢复系数，不同的窗函数可能有不同的取值。

**Comment by zuowanbushiwo** [comment]
@songhui5561  你们代码 https://github.com/athena-team/athena-signal/blob/master/athena_signal/kernels/dios_ssp_share/dios_ssp_share_subband.c#L163
 srv->scale = 1.0f;
 平顶窗的恢复系数不是1.0f， 这个是矩形窗的恢复系数，是不是搞错了？
谢谢，回复！

**Comment by songhui5561** [comment]
窗函数是手动设计，不是严格的平顶窗，而和scale是和它搭配使用的。
你可以手动验证下，通过一次正反变换，看信号幅度是否变化。

**Comment by zuowanbushiwo** [comment]
@songhui5561  好的 ，谢谢了解！

**Comment by zuowanbushiwo** [comment]
宋老师，代码中的subband的实现是参考下面的 Version 4 ,  D=128  M=256  L=768 吗?  这个是 filter bank 的 NPR 吗？
http://www.ws.binghamton.edu/fowler/fowler%20personal%20page/EE521_files/IV-08%20Uniform%20DFT%20Filter%20Bank_2007.pdf

文档version 3 ，Analysis 中使用的窗函数系数是w[i]，那么 Synthesis 中就是 1/w[i] ，为什么 version 4 中不是这么做了？使用的是恢复系数？

subband_filter_coef 是怎么产生的，任何窗函数都可以吗？ 还是需要设计成满足NPR的形式？ 有参考文档吗？
谢谢
