### ISSUE TITLE
关于代码中子带的问题请教2？

### ISSUE THREAD

**Issue by zuowanbushiwo** [athena-team/athena-signal#18]
请问代码中的subband实现是参考下面文档中的 Version 4 吗 , D=128 M=256 L=768 吗? 这个是 filter bank 的 NPR 吗？
http://www.ws.binghamton.edu/fowler/fowler%20personal%20page/EE521_files/IV-08%20Uniform%20DFT%20Filter%20Bank_2007.pdf

文档中version 3 ，Analysis 中使用的窗函数系数是w[i]，那么 Synthesis 中就是 1/w[i] ，为什么 version 4 中不是这么做了？使用的是恢复系数？
subband_filter_coef 是怎么产生的，比如(Hanning , Hamming和Kaiser ）这些常见的窗函数都可以吗？ 还是需要设计成满足NPR一些非线性公式？ 有参考文档吗？看了很多文档都没看到老师这么做的,，看到的文档都是一堆公式求解非线性问题。

仔细看了视频的filter bank部分没讲太深，自己看了很多文档也没理解透彻这部分。

谢谢

**Comment by songhui5561** [comment]
原型滤波器的设计，我们参考过一些论文，核心是下面两篇，还有些由于时间久远我手头没有找到。

“PROTOTYPE FILTER DESIGN FOR OVERSAMPLED SUBBAND ADAPTIVE FILTERING STRUCTURES”.   equation(10)--(12)
“Multirate digital signal processing” by Rabiner. (7.116 -- 7.120)

**Comment by songhui5561** [comment]
原则上滤波器的设计没有固定规则，你提到的常见的窗函数都可以作为原型滤波器。我们这样的设计也是“测试集导向”的，在我们当时的特定数据集上效果稍好一些。

**Comment by zuowanbushiwo** [comment]
谢谢宋老师，圣诞快乐！
