### ISSUE TITLE
athena signal AEC

### ISSUE THREAD

**Issue by mycan12345** [athena-team/athena-signal#21]
Hi All
我发现athena signal AEC和webrtc的AEC相似，请问先他们有什么不同，那些地方有改进，谢谢

**Comment by songhui5561** [comment]
TDE和webtrc基本是一样的，个别地方重新改写过；
线性回声消除部分是自适应滤波的思路，我们采用的是子带自适应滤波，设计了两组自适应滤波器互相backup。残余回声抑制，参考了speex的res模块。

**Comment by mycan12345** [comment]
谢谢回答
