### ISSUE TITLE
I want to change frame size to 10ms buffer, what should I do please?

### ISSUE THREAD

**Issue by zcy618** [athena-team/athena-signal#24]
Dear friends:
1, I notice currently you only support 8ms buffer to process, now I want to change to 10ms buffer, I tried to change some parameters, but I find the programme runs crashed, and the output is all zero, so I want to know what should I change for 10ms buffer?
2, I notice you define subband_filter_coef[] in dios_ssp_share_subband.c file, but I do not know how you get this filter, could you give your algorithm? I see it is not just hanning or hamming windows, I think if I want to change to 10ms buffer, I have to change it, correctly?

Thanks

**Comment by zcy618** [comment]
I have fixed it, close.
But if you have any further comment, please feel free to share it.
Thanks

**Comment by zhuhao528** [comment]
how to fix it，Could you give how you did it？
