### ISSUE TITLE
How can the angle of incidence of the sound source be set manually for MVDR?

### ISSUE THREAD

**Issue by pfeatherstone** [athena-team/athena-signal#8]
How can the angle of incidence of the sound source be set manually for MVDR?

**Comment by songhui5561** [comment]
I see you fix this by updating 'dios_ssp_api'. It works! 
Actually the incidence angle is usually set by DOA module automatically in most cases, so we do not provide this api explicitly at the very start.

**Comment by pfeatherstone** [comment]
@songhui5561 thank you. I have a PR but still not reviewed or merged.

**Comment by songhui5561** [comment]
Merged ！
